# Proyecto Pandas Platzi #

## Numpy ##

In [52]:
import numpy as np

### Numpy array ###

In [2]:
lista=[1,2,3,4,5,6] #*Defino una tupla
arr=np.array(lista) #*Defino el array en base a la tupla
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])  #*Defino una matriz
matriz[0] #*Llamo la primer fila de la matriz
arr[1:3] #*Llamo el segundo y tercer indice del array
matriz[1:,0:2] #*Llamo las filas 2 y 3 con filas 1 y 2

array([[4, 5],
       [7, 8]])

### Tipos de datos ###

In [3]:
arr = np.array([1,2,3,4])
arr.dtype #*Tipo de datos en el array

dtype('int64')

In [4]:
arr = np.array([1,2], dtype='float64') #*Convertir los datos a float
arr

array([1., 2.])

In [5]:
arr = np.array([0,1,2,3,4])
arr=arr.astype(np.bool_) #*Convertir los valores a booleados, todos los numeros a true salvo por el 0
arr

array([False,  True,  True,  True,  True])

### Dimensiones ###

In [6]:
esc=np.array(17) #*definiendo escalar
vec=np.array([1,2,3,4]) #*definiendo vector
mat=np.array([[1,2,3],[3,3,3]]) #*definiendo matriz
ten=np.array([[[1,2,3],[3,3,3]],[[1,2,3],[3,3,3]]])

esc.ndim, vec.ndim, mat.ndim, ten.ndim #*numero de dimensiones

(0, 1, 2, 3)

In [7]:
vec=np.array([1,2,3,4], ndmin=6) #*definiendo las dimensiones de un array
print(vec)
vec.ndim

[[[[[[1 2 3 4]]]]]]


6

In [8]:
exp=np.expand_dims(np.array([1,2,3,4]),axis=0) #*se expande la dimension del vector en el 0-esimo eje.
exp

array([[1, 2, 3, 4]])

In [9]:
vec=np.array([1,2,3,4], ndmin=6)
print(vec)
vec2=np.squeeze(vec) #*comprime a la dimension correcta
vec2

[[[[[[1 2 3 4]]]]]]


array([1, 2, 3, 4])

### Creando arrays ###

In [10]:
list(range(0,10)) #*lista normal de python
np.arange(0,10,2) #*lista de numpy inicia en 0, llega a 10 y va de 2 en 2

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(2) #*array solo de 0's de dimension 1 de largo 2

array([0., 0.])

In [12]:
np.zeros((3,4)) #*matriz 3x4 de 0's

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,3)) #*matriz 3x3 de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,1,4) #*lista longitud 4 de numeros entre 0 y 1

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [15]:
np.eye(5) #*matriz identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(4,4) #*matriz 4x4 de numeros aleatorios

array([[0.06716996, 0.01757192, 0.08111873, 0.45445386],
       [0.37305379, 0.59711474, 0.94076782, 0.47813676],
       [0.00280227, 0.62478905, 0.15431834, 0.9617085 ],
       [0.39995198, 0.33739963, 0.49780935, 0.22483729]])

In [17]:
np.random.randint(14) #*entero alearotio menor a 14

0

In [18]:
np.random.randint(1,25,(5,5)) #*matriz 5x5 de enteros menores a 25 aleatorios

array([[ 2,  2,  4, 16, 12],
       [ 9, 15, 22,  2, 18],
       [22, 15, 24, 20, 19],
       [23,  9, 10, 19,  8],
       [16, 14,  7, 18,  5]])

### Shape y reshape ###

In [19]:
vec=np.array([1,2,3,4])
vec.shape #*arroja longitud cada eje

(4,)

In [20]:
vec=np.array([1,2,3,4,5,6,7,8])
vec.reshape(4,2) #*reorganiza el array a una matriz de 4x2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
vec=np.array([1,2,3,4,5,6,7,8])
np.reshape(vec,(2,4),'C') #*reorganizar como en el lenguaje C

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
vec=np.array([1,2,3,4,5,6,7,8])
np.reshape(vec,(2,4),'F') #*reorganizar como en Fortrand (mas feo)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [23]:
vec=np.array([1,2,3,4,5,6,7,8])
np.reshape(vec,(2,4),'A') #*reorganizar como el pc lo determine mejor

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Funciones principales de numpy ###

In [24]:
matriz=np.random.rand(4,4)
matriz

array([[0.82721721, 0.97254011, 0.38132049, 0.71267562],
       [0.61994923, 0.12439014, 0.31990838, 0.06690762],
       [0.39954704, 0.83708344, 0.24609935, 0.84598991],
       [0.60458543, 0.72221446, 0.94778761, 0.38975549]])

In [25]:
matriz.max() #*maximo de la matriz

0.9725401089495365

In [26]:
matriz.max(0) #*maximo de la matriz en cada arreglo del 0-esimo eje

array([0.82721721, 0.97254011, 0.94778761, 0.84598991])

In [27]:
matriz.argmax() #*indice del maximo

1

In [28]:
matriz.argmax(1) #*indice del maximo en el 1-esimo eje

array([1, 0, 3, 2])

con min se hace lo mismo para el minimo

In [29]:
vec=np.array([10,2,3,4,5,6,7,8])
vec.ptp(0) #*diferencia del maximo y el minimo en el 0-esimo eje

8

In [30]:
vec.sort() #*ordena de menor a mayor
vec

array([ 2,  3,  4,  5,  6,  7,  8, 10])

In [31]:
np.percentile(vec,50) #*percentil 50 del vec

5.5

In [32]:
np.median(vec) #*mediana

5.5

In [33]:
np.std(vec) #*desciacion estandar

2.496873044429772

In [34]:
np.var(vec) #*varianza de vec

6.234375

In [35]:
np.mean(vec) #*media

5.625

In [36]:
a=np.array([[1,2],[3,4]])
b=np.array([5,4])
b=np.expand_dims(b,axis=0)

np.concatenate((a,b),axis=0) #*pegar arrays en el 0-esimo eje

array([[1, 2],
       [3, 4],
       [5, 4]])

### Copy ###

In [37]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

observe el siguiente error

In [38]:
pedacito=arr[2:5]
pedacito[:]=0
pedacito

array([0, 0, 0])

In [39]:
arr

array([ 0,  1,  0,  0,  0,  5,  6,  7,  8,  9, 10])

dañamos la información de arr, la solución es usar copy()

In [40]:
arr=np.arange(0,11)
pedacito=arr[2:5].copy()
pedacito[:]=0
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Condiciones ###

In [41]:
arr=np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [42]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [43]:
arr[(arr<4) & (arr==6)]

array([], dtype=int8)

In [44]:
arr[arr>5]=0
arr

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0], dtype=int8)

### Operaciones ###

In [45]:
arr=np.linspace(1,20,20)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [46]:
arr2=arr.copy()*2 #*se pueden hacer operaciones facilmente
arr2

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40.])

In [47]:
arr @ arr2 #*producto matricial, en este caso producto punto

5740.0

## Pandas ##

In [48]:
import pandas as pd

### Series y dataframes en pandas ###

In [49]:
psg_players=pd.Series(['Navas','Mbappe','Neymar','Messi'], index=[1,7,10,30])
psg_players


1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [50]:
dict={1:'navas',7:'Mbappe',10:'Neymar',30:'Messi'}
psg_players=pd.Series(dict)

In [51]:
psg_players[30]
psg_players[0] #!no se puede llamar asi, ese no es un indice valido


KeyError: 0

In [ ]:
dict = {'Jugador':['Navas','Mbappe','Neymar','Messi'], 'Altura':[183.0, 170.0, 170.0, 163.0], 'Goles':[2, 200, 150, 500]} #*defino dataframe
df_players=pd.DataFrame(dict, index=[1,7,10,30]) #*defino indices del dataframe
df_players

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    150
30   Messi   163.0    500

In [ ]:
df_players.columns #*columnas

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [ ]:
df_players.index #*indices

Index([1, 7, 10, 30], dtype='int64')

### Leer archivos CSV y JSON con pandas ###

In [ ]:
df_books=pd.read_csv('/root/Platzi/CursoNumpyPandas/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv', sep=',', header=0, names=['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])
#*defino datafrfame con pandas leyendo un cvs. el separados es , y empiesa a leerlo desde la columna 0. Establece los nombres.
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

### Filtrado con loc y iloc ###

In [ ]:
df_books[0:4] #*filtrar filas

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [ ]:
df_books[['Name','Author']] #*filtrar columnas

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  
0                    JJ Smith  
1                Stephen King  
2          Jordan B. Peterson  
3               George Orwell  
4    National Geographic Kids  
..                        ...  
545               Jeff Kinney  
546               Jen Sincero  
547               Jen Sincero  
548               Jen Sincero  
549               Jen Sincero  

[550 rows x 2 columns]

para filtrar filas y columnas al tiempo se usa loc y iloc

In [ ]:
df_books.loc[0:4, ['Name', 'Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [ ]:
df_books.loc[0:4, ['Reviews']] *-1 #*se pueden hacer operaciones

Reviews
0   -17350
1    -2052
2   -18979
3   -21424
4    -7665

In [ ]:
df_books.loc[:,['Author']]=='JJ Smith' #*Filtrar la culomna de autor donde esta JJ Smith

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

el filtrado con loc usa los indices del dataframe, pero iloc usa indices como los de numpy

In [ ]:
df_books.iloc[0:5,2:6] #* 

User Rating  Reviews  Price  Year
0          4.7    17350      8  2016
1          4.6     2052     22  2011
2          4.7    18979     15  2018
3          4.7    21424      6  2017
4          4.8     7665     12  2019

### Agregar o eliminar datos con pandas ###

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [ ]:
df_books.drop('Genre',axis=1) #*se elimina Genre, axis indica la dimension de donde estamos eliminando la informacion
#*este comando solo filtra pero no altera el dataframe original

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [ ]:
df_books.drop('Genre', axis=1, inplace=True)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [ ]:
df_books.drop(range(5,19),axis=0) #* al poner axis=0 se esta eliminando de la dimension 0, osea las filas

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[536 rows x 6 columns]

In [ ]:
df_books['Nueva Col'] = np.nan #*agregando columna hasta la izquierda.
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Nueva Col  
0                    JJ Smith          4.7    17350      8  2016        NaN  
1                Stephen King          4.6     2052     22  2011        NaN  
2          Jordan B. Peterson          4.7    18979     15  2018        NaN  
3               George Orwell          4.7    21424      6  2017        NaN  
4    National Geographic Kids          4.8     7665     12  2019        NaN  
..                        ...          ...      ...    ...   ...        ...  
545               Jeff Kinney          4.9     9413      8  2019        NaN  
546               Jen Sincero          4.7    14331      8  2016        NaN  
547               Jen Sincero          4.7    14331      8  2017        NaN  
548               Jen Sincero          4.7    14331      8  2018        NaN  
549               Jen Sincero          4.7    14331      8  2019        NaN  

[550 rows x 7 columns]

In [ ]:
df_books.shape[0] #*longitud de la 0-esima dimension

550

In [ ]:
listita=range(0,df_books.shape[0])
df_books['OtraCol']=listita #*solo se pueden agregar nuevas columnas que tienen la misma longitud
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Nueva Col  \
0                    JJ Smith          4.7    17350      8  2016        NaN   
1                Stephen King          4.6     2052     22  2011        NaN   
2          Jordan B. Peterson          4.7    18979     15  2018        NaN   
3               George Orwell          4.7    21424      6  2017        NaN   
4    National Geographic Kids          4.8     7665     12  2019        NaN   
..                        ...          ...      ...    ...   ...        ...   
545               Jeff Kinney          4.9     9413      8  2019        NaN   
546               Jen Sincero          4.7    14331      8  2016        NaN   
547               Jen Sincero          4.7    14331      8  2017        NaN   
548               Jen Sincero          4.7    14331      8  2018        NaN   
549               Jen Sincero          4.7    14331      8  2019        NaN   

     OtraCol  
0          0  
1          1  
2          2  
3          3  
4          4  
..       ...  
545      545  
546      546  
547      547  
548      548  
549      549  

[550 rows x 8 columns]

In [ ]:
pd.concat([df_books,df_books], axis=0) #*concat para pegar dataframes

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Nueva Col  \
0                    JJ Smith          4.7    17350      8  2016        NaN   
1                Stephen King          4.6     2052     22  2011        NaN   
2          Jordan B. Peterson          4.7    18979     15  2018        NaN   
3               George Orwell          4.7    21424      6  2017        NaN   
4    National Geographic Kids          4.8     7665     12  2019        NaN   
..                        ...          ...      ...    ...   ...        ...   
545               Jeff Kinney          4.9     9413      8  2019        NaN   
546               Jen Sincero          4.7    14331      8  2016        NaN   
547               Jen Sincero          4.7    14331      8  2017        NaN   
548               Jen Sincero          4.7    14331      8  2018        NaN   
549               Jen Sincero          4.7    14331      8  2019        NaN   

     OtraCol  
0          0  
1          1  
2          2  
3          3  
4          4  
..       ...  
545      545  
546      546  
547      547  
548      548  
549      549  

[1100 rows x 8 columns]

### Manejo de datos nulos ###

In [ ]:
dict = {'Col1':[1,2,3,np.nan],
'Col2':[4, np.nan,6,7],
'Col3':['a','b','c', None]}

df=pd.DataFrame(dict)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [ ]:
df.isnull()*1 #*isnull para convertir a booleanos sihay o no booleanos, *1 para pasarlo a binario

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [ ]:
df.fillna('Missing') #*fillna para pasar nulos a algo especifico

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [ ]:
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [ ]:
df.interpolate() #*python completa los valores nulos interpolandolos.

/tmp/ipykernel_55172/3694035331.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate() #*python completa los valores nulos interpolandolos.


Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [ ]:
df.dropna() #*elimina las filas con valores nulos

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

### Filtrado por condiciones ###

In [ ]:
m2016=df_books['Year']>2016
df_books[m2016] #*filtrado

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Nueva Col  \
2          Jordan B. Peterson          4.7    18979     15  2018        NaN   
3               George Orwell          4.7    21424      6  2017        NaN   
4    National Geographic Kids          4.8     7665     12  2019        NaN   
7                 Amor Towles          4.7    19699     15  2017        NaN   
8                 James Comey          4.7     5983      3  2018        NaN   
..                        ...          ...      ...    ...   ...        ...   
544             R. J. Palacio          4.8    21625      9  2017        NaN   
545               Jeff Kinney          4.9     9413      8  2019        NaN   
547               Jen Sincero          4.7    14331      8  2017        NaN   
548               Jen Sincero          4.7    14331      8  2018        NaN   
549               Jen Sincero          4.7    14331      8  2019        NaN   

     OtraCol  
2          2  
3          3  
4          4  
7          7  
8          8  
..       ...  
544      544  
545      545  
547      547  
548      548  
549      549  

[150 rows x 8 columns]

### Funciones principales de pandas ###

In [ ]:
df_books.info() #*info god

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Nueva Col    0 non-null      float64
 7   OtraCol      550 non-null    int64  
dtypes: float64(2), int64(4), object(2)
memory usage: 34.5+ KB


In [ ]:
df_books.describe()

User Rating       Reviews       Price         Year  Nueva Col  \
count   550.000000    550.000000  550.000000   550.000000        0.0   
mean      4.618364  11953.281818   13.100000  2014.000000        NaN   
std       0.226980  11731.132017   10.842262     3.165156        NaN   
min       3.300000     37.000000    0.000000  2009.000000        NaN   
25%       4.500000   4058.000000    7.000000  2011.000000        NaN   
50%       4.700000   8580.000000   11.000000  2014.000000        NaN   
75%       4.800000  17253.250000   16.000000  2017.000000        NaN   
max       4.900000  87841.000000  105.000000  2019.000000        NaN   

          OtraCol  
count  550.000000  
mean   274.500000  
std    158.915596  
min      0.000000  
25%    137.250000  
50%    274.500000  
75%    411.750000  
max    549.000000

In [ ]:
df_books.memory_usage(deep=True)

Index            132
Name           55233
Author         34622
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Nueva Col       4400
OtraCol         4400
dtype: int64

In [ ]:
df_books.value_counts

<bound method DataFrame.value_counts of                                                   Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Nueva Col  \
0                    JJ Smith          4.7    17350      8  2016        NaN   
1                Stephen King          4.6     2052     22  2011        NaN   
2          Jordan B. Peter

In [ ]:
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Nueva Col  \
0                    JJ Smith          4.7    17350      8  2016        NaN   
1                Stephen King          4.6     2052     22  2011        NaN   
2          Jordan B. Peterson          4.7    18979     15  2018        NaN   
3               George Orwell          4.7    21424      6  2017        NaN   
4    National Geographic Kids          4.8     7665     12  2019        NaN   
..                        ...          ...      ...    ...   ...        ...   
545               Jeff Kinney          4.9     9413      8  2019        NaN   
546               Jen Sincero          4.7    14331      8  2016        NaN   
547               Jen Sincero          4.7    14331      8  2017        NaN   
548               Jen Sincero          4.7    14331      8  2018        NaN   
549               Jen Sincero          4.7    14331      8  2019        NaN   

     OtraCol  
0          0  
1          1  
2          2  
3          3  
4          4  
..       ...  
545      545  
546      546  
547      547  
548      548  
549      549  

[550 rows x 8 columns]

In [ ]:
df_books.sort_values('Reviews', ascending=True)

Name             Author  \
78   Divine Soul Mind Body Healing and Transmission...       Zhi Gang Sha   
300  Soul Healing Miracles: Ancient and New Sacred ...       Zhi Gang Sha   
121                    George Washington's Sacred Fire  Peter A. Lillback   
512                             True Compass: A Memoir  Edward M. Kennedy   
359  The Daily Show with Jon Stewart Presents Earth...        Jon Stewart   
..                                                 ...                ...   
32                                            Becoming     Michelle Obama   
33                                            Becoming     Michelle Obama   
383                              The Girl on the Train      Paula Hawkins   
382                              The Girl on the Train      Paula Hawkins   
534                            Where the Crawdads Sing        Delia Owens   

     User Rating  Reviews  Price  Year  Nueva Col  OtraCol  
78           4.6       37      6  2009        NaN       78  
300          4.6      220     17  2013        NaN      300  
121          4.5      408     20  2010        NaN      121  
512          4.5      438     15  2009        NaN      512  
359          4.4      440     11  2010        NaN      359  
..           ...      ...    ...   ...        ...      ...  
32           4.8    61133     11  2018        NaN       32  
33           4.8    61133     11  2019        NaN       33  
383          4.1    79446      7  2016        NaN      383  
382          4.1    79446     18  2015        NaN      382  
534          4.8    87841     15  2019        NaN      534  

[550 rows x 8 columns]

### groupby ###

In [ ]:
df_books.groupby('Author').count().loc['Michelle Obama']

Name           2
User Rating    2
Reviews        2
Price          2
Year           2
Nueva Col      0
OtraCol        2
Name: Michelle Obama, dtype: int64

In [ ]:
df_books.groupby('Name').agg(['min','max','sum','count']).drop(['Author','Year','Nueva Col','OtraCol'], axis=1)

User Rating             \
                                                           min  max   sum   
Name                                                                        
10-Day Green Smoothie Cleanse                              4.7  4.7   4.7   
11/22/63: A Novel                                          4.6  4.6   4.6   
12 Rules for Life: An Antidote to Chaos                    4.7  4.7   4.7   
1984 (Signet Classics)                                     4.7  4.7   4.7   
5,000 Awesome Facts (About Everything!) (Nation...         4.8  4.8   4.8   
...                                                        ...  ...   ...   
Winter of the World: Book Two of the Century Tr...         4.5  4.5   4.5   
Women Food and God: An Unexpected Path to Almos...         4.2  4.2   4.2   
Wonder                                                     4.8  4.8  24.0   
Wrecking Ball (Diary of a Wimpy Kid Book 14)               4.9  4.9   4.9   
You Are a Badass: How to Stop Doubting Your Gre...         4.7  4.7  18.8   

                                                         Reviews         \
                                                   count     min    max   
Name                                                                      
10-Day Green Smoothie Cleanse                          1   17350  17350   
11/22/63: A Novel                                      1    2052   2052   
12 Rules for Life: An Antidote to Chaos                1   18979  18979   
1984 (Signet Classics)                                 1   21424  21424   
5,000 Awesome Facts (About Everything!) (Nation...     1    7665   7665   
...                                                  ...     ...    ...   
Winter of the World: Book Two of the Century Tr...     1   10760  10760   
Women Food and God: An Unexpected Path to Almos...     1    1302   1302   
Wonder                                                 5   21625  21625   
Wrecking Ball (Diary of a Wimpy Kid Book 14)           1    9413   9413   
You Are a Badass: How to Stop Doubting Your Gre...     4   14331  14331   

                                                                 Price      \
                                                       sum count   min max   
Name                                                                         
10-Day Green Smoothie Cleanse                        17350     1     8   8   
11/22/63: A Novel                                     2052     1    22  22   
12 Rules for Life: An Antidote to Chaos              18979     1    15  15   
1984 (Signet Classics)                               21424     1     6   6   
5,000 Awesome Facts (About Everything!) (Nation...    7665     1    12  12   
...                                                    ...   ...   ...  ..   
Winter of the World: Book Two of the Century Tr...   10760     1    15  15   
Women Food and God: An Unexpected Path to Almos...    1302     1    11  11   
Wonder                                              108125     5     9   9   
Wrecking Ball (Diary of a Wimpy Kid Book 14)          9413     1     8   8   
You Are a Badass: How to Stop Doubting Your Gre...   57324     4     8   8   

                                                              
                                                   sum count  
Name                                                          
10-Day Green Smoothie Cleanse                        8     1  
11/22/63: A Novel                                   22     1  
12 Rules for Life: An Antidote to Chaos             15     1  
1984 (Signet Classics)                               6     1  
5,000 Awesome Facts (About Everything!) (Nation...  12     1  
...                                                 ..   ...  
Winter of the World: Book Two of the Century Tr...  15     1  
Women Food and God: An Unexpected Path to Almos...  11     1  
Wonder                                              45     5  
Wrecking Ball (Diary of a Wimpy Kid Book 14)         8     1  
You Are a

In [ ]:
df_books.groupby('Name').agg({'Reviews':['mean'],'Price':['min','max']}) #*GOOOOOOOODDDDDDDDD

Reviews Price    
                                                       mean   min max
Name                                                                 
10-Day Green Smoothie Cleanse                       17350.0     8   8
11/22/63: A Novel                                    2052.0    22  22
12 Rules for Life: An Antidote to Chaos             18979.0    15  15
1984 (Signet Classics)                              21424.0     6   6
5,000 Awesome Facts (About Everything!) (Nation...   7665.0    12  12
...                                                     ...   ...  ..
Winter of the World: Book Two of the Century Tr...  10760.0    15  15
Women Food and God: An Unexpected Path to Almos...   1302.0    11  11
Wonder                                              21625.0     9   9
Wrecking Ball (Diary of a Wimpy Kid Book 14)         9413.0     8   8
You Are a Badass: How to Stop Doubting Your Gre...  14331.0     8   8

[351 rows x 3 columns]

### Merge y Concat ###

In [ ]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2','A3'],
        'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']})


df2 = pd.DataFrame({'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']})

In [ ]:
pd.concat([df1,df2], ignore_index=True) #*concat los pega sin mas

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2],axis=1) #* axis 0 por defecto

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [ ]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

izq

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

merge se centra en las coinsidencias en las columnas

In [ ]:
izq.merge(der) 

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [ ]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key2' : ['k0', 'k1', 'k2','k3'],
'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [ ]:
izq.merge(der, left_on='key', right_on='key2') #*asi se agrupa dataframes donde las columnas no tienen la misma key

key   A   B key2   C   D
0  k0  A0  B0   k0  C0  D0
1  k1  A1  B1   k1  C1  D1
2  k2  A2  B2   k2  C2  D2
3  k3  A3  B3   k3  C3  D3

In [ ]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key2' : ['k0', 'k1', 'k2',np.nan],
'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [ ]:
izq.merge(der, left_on='key', right_on='key2', how='left') #*por defecto el merge es inner, con el how se cambia a left, right, inner o outer

key   A   B key2    C    D
0  k0  A0  B0   k0   C0   D0
1  k1  A1  B1   k1   C1   D1
2  k2  A2  B2   k2   C2   D2
3  k3  A3  B3  NaN  NaN  NaN

### Join ###

join, a diferencia de merge, se centra en los indices y no en las columnas

In [ ]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
'B':['B0','B1','B2']},
index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
'D':['D0','D1','D2']},
index=['k0','k2','k3']) 

izq

A   B
k0  A0  B0
k1  A1  B1
k2  A2  B2

In [ ]:
izq.join(der, how='outer') #*por defecto el how es left. Join completa con valores nulos

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

### Pivot y Melt ###

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.pivot_table(index='Name',columns='Genre',values='Price') #*God de lo God, literalmente God

Genre                                               Fiction  Non Fiction
Name                                                                    
10-Day Green Smoothie Cleanse                           NaN          8.0
11/22/63: A Novel                                      22.0          NaN
12 Rules for Life: An Antidote to Chaos                 NaN         15.0
1984 (Signet Classics)                                  6.0          NaN
5,000 Awesome Facts (About Everything!) (Nation...      NaN         12.0
...                                                     ...          ...
Winter of the World: Book Two of the Century Tr...     15.0          NaN
Women Food and God: An Unexpected Path to Almos...      NaN         11.0
Wonder                                                  9.0          NaN
Wrecking Ball (Diary of a Wimpy Kid Book 14)            8.0          NaN
You Are a Badass: How to Stop Doubting Your Gre...      NaN          8.0

[351 rows x 2 columns]

In [ ]:
df_books.pivot_table(index='Genre',columns='Year', values='Price',aggfunc='median') #*la funcion de agregacion dice como se cuentan los valores

Year         2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019
Genre                                                                        
Fiction      11.5  10.0  10.0  11.0  12.0   8.0   9.0   9.0   7.5   8.0   8.0
Non Fiction  13.5  14.0  15.0  16.0  13.0  15.0   9.0  10.0  11.0  11.0  11.0

### Melt ###

In [ ]:
df_books[['Name','Genre','Price']].melt() #*melt convierte las columnas en filas y crra dos nuevas columnas donde especifican el tipo de variable y el valor que tienen

variable                                              value
0        Name                      10-Day Green Smoothie Cleanse
1        Name                                  11/22/63: A Novel
2        Name            12 Rules for Life: An Antidote to Chaos
3        Name                             1984 (Signet Classics)
4        Name  5,000 Awesome Facts (About Everything!) (Natio...
...       ...                                                ...
1645    Price                                                  8
1646    Price                                                  8
1647    Price                                                  8
1648    Price                                                  8
1649    Price                                                  8

[1650 rows x 2 columns]

In [ ]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

### Apply ###

In [ ]:
df_books['NewCol']=df_books['Price'].apply(lambda i:i*2)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     NewCol  
0        16  
1        44  
2        30  
3        12  
4        24  
..      ...  
545      16  
546      16  
547      16  
548      16  
549      16  

[550 rows x 8 columns]

In [ ]:
df_books.apply(lambda x : x['Price']*2 if x['Genre']=='Fiction' else x['Price'], axis=1) #*god
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     NewCol  
0        16  
1        44  
2        30  
3        12  
4        24  
..      ...  
545      16  
546      16  
547      16  
548      16  
549      16  

[550 rows x 8 columns]